language: go
os:
  - linux
  - osx
go:
  - 1.13.x

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org make nodeup examples test

jobs:
  include:
    - name: Verify
      os: linux
      go: 1.13.x
      script:
        - GOPROXY=https://proxy.golang.org make travis-ci
